apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-demo-customer-portal
  namespace: customer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dr-demo-customer-portal
  template:
    metadata:
      labels:
        app: dr-demo-customer-portal
    spec:
      containers:
        - name: dr-demo-customer-portal
          image: ghcr.io/oodles-noodles/dr-demo-customer-portal:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dr-demo-customer-portal-db
                  key: url
